export const ACTION = {
    SET_CURRENT_ROUTE: "SET_CURRENT_ROUTE",
    GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
    GET_SINGLE_NOTIFICATION: "GET_SINGLE_NOTIFICATION",
    READ_NOTIFICATIONS: "READ_NOTIFICATIONS",
    READ_MESSAGES: "READ_MESSAGES",
    GET_UNREAD_MESSAGE: "GET_UNREAD_MESSAGE"
};