export const ACTION = {
    GET_SOME_DATA: "GET_SOME_DATA",
    GET_SUGGESTED_PAGES: "GET_SUGGESTED_PAGES",
    CHANGE_TAB: "CHANGE_TAB",
    GET_PROFILE: "GET_PROFILE",
    UPDATE_PROFILE_PIC: "UPDATE_PROFILE_PIC",
    GET_FOLLOWERS: "GET_FOLLOWERS",
    GET_FOLLOWING: "GET_FOLLOWING"
};